version: '3.9'
services:
  postgres:
    container_name: postgresql-messenger
    image: postgres:15.1-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/messenger

#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - "80:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: user@domain.com
#      PGADMIN_DEFAULT_PASSWORD: SuperSecret

volumes:
  pgdata: